In [7]:
import polars as pl
import polars_st as st
from polars_st import geom, geometry

In [5]:
data = pl.scan_parquet("../data/processed/firms_noaa20.parquet")

In [6]:
data.head().collect()

shape: (5, 15)
┌──────────┬───────────┬────────────┬──────┬───┬────────────┬──────┬──────────┬────────────────────┐
│ latitude ┆ longitude ┆ bright_ti4 ┆ scan ┆ … ┆ bright_ti5 ┆ frp  ┆ daynight ┆ acquired_at_utc    │
│ ---      ┆ ---       ┆ ---        ┆ ---  ┆   ┆ ---        ┆ ---  ┆ ---      ┆ ---                │
│ f64      ┆ f64       ┆ f64        ┆ f64  ┆   ┆ f64        ┆ f64  ┆ str      ┆ datetime[μs, UTC]  │
╞══════════╪═══════════╪════════════╪══════╪═══╪════════════╪══════╪══════════╪════════════════════╡
│ -8.79831 ┆ 140.69357 ┆ 331.79     ┆ 0.44 ┆ … ┆ 295.91     ┆ 3.73 ┆ D        ┆ 2026-08-24         │
│          ┆           ┆            ┆      ┆   ┆            ┆      ┆          ┆ 03:49:00 UTC       │
│ -8.71738 ┆ 140.74724 ┆ 330.69     ┆ 0.43 ┆ … ┆ 290.74     ┆ 1.54 ┆ D        ┆ 2026-08-24         │
│          ┆           ┆            ┆      ┆   ┆            ┆      ┆          ┆ 03:49:00 UTC       │
│ -8.34927 ┆ 138.0038  ┆ 336.22     ┆ 0.33 ┆ … ┆ 302.29     ┆ 5.4  ┆ D        ┆ 2026-08-24         │
│          ┆           ┆            ┆      ┆   ┆            ┆      ┆          ┆ 03:49:00 UTC       │
│ -8.3187  ┆ 137.76657 ┆ 332.43     ┆ 0.34 ┆ … ┆ 299.93     ┆ 2.74 ┆ D        ┆ 2026-08-24         │
│          ┆           ┆            ┆      ┆   ┆            ┆      ┆          ┆ 03:49:00 UTC       │
│ -8.30191 ┆ 137.89424 ┆ 338.57     ┆ 0.33 ┆ … ┆ 301.05     ┆ 4.29 ┆ D        ┆ 2026-08-24         │
│          ┆           ┆            ┆      ┆   ┆            ┆      ┆          ┆ 03:49:00 UTC       │
└──────────┴───────────┴────────────┴──────┴───┴────────────┴──────┴──────────┴────────────────────┘

In [16]:
data = data.with_columns(
    geometry=st.point(
        pl.concat_arr("longitude", "latitude"),
        srid=4326
    )
)

prov = st.read_file("../data/boundaries/geoBoundaries-IDN-ADM1-provinces.geojson")
prov = prov.select(
    pl.col("shapeName").alias("province"),
    "geometry"
)

/tmp/ipykernel_233868/72675481.py:8: FutureWarning: from_arrow(<ArrowStreamExportable>) will return a Series instead of a DataFrame in 2.0. To avoid this warning, pass the ArrowStreamExportable to either `pl.DataFrame` or `pl.Series` instead based on your desired output type.
  prov = st.read_file("../data/boundaries/geoBoundaries-IDN-ADM1-provinces.geojson")

In [17]:
print(prov.schema)
print(prov.head())

Schema({'province': String, 'geometry': Binary})
shape: (5, 2)
┌────────────────────┬─────────────────────────────────┐
│ province           ┆ geometry                        │
│ ---                ┆ ---                             │
│ str                ┆ binary                          │
╞════════════════════╪═════════════════════════════════╡
│ Bali               ┆ b"\x01\x06\x00\x00\x20\xe6\x10… │
│ West Nusa Tenggara ┆ b"\x01\x06\x00\x00\x20\xe6\x10… │
│ Banten             ┆ b"\x01\x06\x00\x00\x20\xe6\x10… │
│ Central Java       ┆ b"\x01\x06\x00\x00\x20\xe6\x10… │
│ West Java          ┆ b"\x01\x03\x00\x00\x20\xe6\x10… │
└────────────────────┴─────────────────────────────────┘

In [27]:
joined = (data.collect()
          .st.sjoin(
                prov,
                how="left",
                predicate="contains"
            )
          .drop("geometry_right")
          )

/tmp/ipykernel_233868/2806564407.py:2: DeprecationWarning: the default behavior of `how='horizontal'` for `concat` is deprecated and will require equal heights in the next breaking release. Use `how='horizontal_extend'` to keep the current behavior.
(Deprecated in version 1.42.1)
  .st.sjoin(

In [28]:
print(joined.schema)
print(joined.head())

Schema({'latitude': Float64, 'longitude': Float64, 'bright_ti4': Float64, 'scan': Float64, 'track': Float64, 'acq_date': String, 'acq_time': Int64, 'satellite': String, 'instrument': String, 'confidence': String, 'version': String, 'bright_ti5': Float64, 'frp': Float64, 'daynight': String, 'acquired_at_utc': Datetime(time_unit='us', time_zone='UTC'), 'geometry': Binary, 'province': String})
shape: (5, 17)
┌──────────┬───────────┬────────────┬──────┬───┬──────────┬──────────────┬──────────────┬──────────┐
│ latitude ┆ longitude ┆ bright_ti4 ┆ scan ┆ … ┆ daynight ┆ acquired_at_ ┆ geometry     ┆ province │
│ ---      ┆ ---       ┆ ---        ┆ ---  ┆   ┆ ---      ┆ utc          ┆ ---          ┆ ---      │
│ f64      ┆ f64       ┆ f64        ┆ f64  ┆   ┆ str      ┆ ---          ┆ binary       ┆ str      │
│          ┆           ┆            ┆      ┆   ┆          ┆ datetime[μs, ┆              ┆          │
│          ┆           ┆            ┆      ┆   ┆          ┆ UTC]         ┆              ┆          │
╞══════════╪═══════════╪════════════╪══════╪═══╪══════════╪══════════════╪══════════════╪══════════╡
│ -8.79831 ┆ 140.69357 ┆ 331.79     ┆ 0.44 ┆ … ┆ D        ┆ 2026-08-24   ┆ b"\x01\x01\x ┆ Papua    │
│          ┆           ┆            ┆      ┆   ┆          ┆ 03:49:00 UTC ┆ 00\x00\x20\x ┆          │
│          ┆           ┆            ┆      ┆   ┆          ┆              ┆ e6\x10…      ┆          │
│ -8.71738 ┆ 140.74724 ┆ 330.69     ┆ 0.43 ┆ … ┆ D        ┆ 2026-08-24   ┆ b"\x01\x01\x ┆ Papua    │
│          ┆           ┆            ┆      ┆   ┆          ┆ 03:49:00 UTC ┆ 00\x00\x20\x ┆          │
│          ┆           ┆            ┆      ┆   ┆          ┆              ┆ e6\x10…      ┆          │
│ -8.34927 ┆ 138.0038  ┆ 336.22     ┆ 0.33 ┆ … ┆ D        ┆ 2026-08-24   ┆ b"\x01\x01\x ┆ Papua    │
│          ┆           ┆            ┆      ┆   ┆          ┆ 03:49:00 UTC ┆ 00\x00\x20\x ┆          │
│          ┆           ┆            ┆      ┆   ┆          ┆              ┆ e6\x10…      ┆          │
│ -8.3187  ┆ 137.76657 ┆ 332.43     ┆ 0.34 ┆ … ┆ D        ┆ 2026-08-24   ┆ b"\x01\x01\x ┆ Papua    │
│          ┆           ┆            ┆      ┆   ┆          ┆ 03:49:00 UTC ┆ 00\x00\x20\x ┆          │
│          ┆           ┆            ┆      ┆   ┆          ┆              ┆ e6\x10…      ┆          │
│ -8.30191 ┆ 137.89424 ┆ 338.57     ┆ 0.33 ┆ … ┆ D        ┆ 2026-08-24   ┆ b"\x01\x01\x ┆ Papua    │
│          ┆           ┆            ┆      ┆   ┆          ┆ 03:49:00 UTC ┆ 00\x00\x20\x ┆          │
│          ┆           ┆            ┆      ┆   ┆          ┆              ┆ e6\x10…      ┆          │
└──────────┴───────────┴────────────┴──────┴───┴──────────┴──────────────┴──────────────┴──────────┘

In [31]:
indo_only = pl.read_parquet("../data/processed/firms_noaa20_indonesia.parquet")

In [33]:
indo_only.head()

shape: (5, 18)
┌──────────┬───────────┬────────────┬──────┬───┬─────────────┬─────────────┬──────────┬────────────┐
│ latitude ┆ longitude ┆ bright_ti4 ┆ scan ┆ … ┆ acquired_at ┆ geometry    ┆ province ┆ kabupaten_ │
│ ---      ┆ ---       ┆ ---        ┆ ---  ┆   ┆ _utc        ┆ ---         ┆ ---      ┆ kota       │
│ f64      ┆ f64       ┆ f64        ┆ f64  ┆   ┆ ---         ┆ binary      ┆ str      ┆ ---        │
│          ┆           ┆            ┆      ┆   ┆ datetime[μs ┆             ┆          ┆ str        │
│          ┆           ┆            ┆      ┆   ┆ , UTC]      ┆             ┆          ┆            │
╞══════════╪═══════════╪════════════╪══════╪═══╪═════════════╪═════════════╪══════════╪════════════╡
│ -8.79831 ┆ 140.69357 ┆ 331.79     ┆ 0.44 ┆ … ┆ 2026-08-24  ┆ b"\x01\x01\ ┆ Papua    ┆ Merauke    │
│          ┆           ┆            ┆      ┆   ┆ 03:49:00    ┆ x00\x00\x20 ┆          ┆            │
│          ┆           ┆            ┆      ┆   ┆ UTC         ┆ \xe6\x10…   ┆          ┆            │
│ -8.71738 ┆ 140.74724 ┆ 330.69     ┆ 0.43 ┆ … ┆ 2026-08-24  ┆ b"\x01\x01\ ┆ Papua    ┆ Merauke    │
│          ┆           ┆            ┆      ┆   ┆ 03:49:00    ┆ x00\x00\x20 ┆          ┆            │
│          ┆           ┆            ┆      ┆   ┆ UTC         ┆ \xe6\x10…   ┆          ┆            │
│ -8.34927 ┆ 138.0038  ┆ 336.22     ┆ 0.33 ┆ … ┆ 2026-08-24  ┆ b"\x01\x01\ ┆ Papua    ┆ Merauke    │
│          ┆           ┆            ┆      ┆   ┆ 03:49:00    ┆ x00\x00\x20 ┆          ┆            │
│          ┆           ┆            ┆      ┆   ┆ UTC         ┆ \xe6\x10…   ┆          ┆            │
│ -8.3187  ┆ 137.76657 ┆ 332.43     ┆ 0.34 ┆ … ┆ 2026-08-24  ┆ b"\x01\x01\ ┆ Papua    ┆ Merauke    │
│          ┆           ┆            ┆      ┆   ┆ 03:49:00    ┆ x00\x00\x20 ┆          ┆            │
│          ┆           ┆            ┆      ┆   ┆ UTC         ┆ \xe6\x10…   ┆          ┆            │
│ -8.30191 ┆ 137.89424 ┆ 338.57     ┆ 0.33 ┆ … ┆ 2026-08-24  ┆ b"\x01\x01\ ┆ Papua    ┆ Merauke    │
│          ┆           ┆            ┆      ┆   ┆ 03:49:00    ┆ x00\x00\x20 ┆          ┆            │
│          ┆           ┆            ┆      ┆   ┆ UTC         ┆ \xe6\x10…   ┆          ┆            │
└──────────┴───────────┴────────────┴──────┴───┴─────────────┴─────────────┴──────────┴────────────┘

In [36]:
daily_kabkot = pl.read_parquet("../data/analytics/daily_kabupaten_kota.parquet")
daily_prov = pl.read_parquet("../data/analytics/daily_province.parquet")
firms30d = pl.read_parquet("../data/analytics/firms_30d.parquet")

In [43]:
print(daily_kabkot.shape)
display(daily_kabkot.head())
print(daily_prov.shape)
display(daily_prov.head())
print(firms30d.shape)
display(firms30d.head())

(6947, 7)

shape: (5, 7)
┌────────────┬────────────┬─────────────────┬───────────────┬────────────────┬───────────┬─────────┐
│ acq_date   ┆ province   ┆ kabupaten_kota  ┆ hotspot_count ┆ high_confidenc ┆ total_frp ┆ max_frp │
│ ---        ┆ ---        ┆ ---             ┆ ---           ┆ e_count        ┆ ---       ┆ ---     │
│ str        ┆ str        ┆ str             ┆ u32           ┆ ---            ┆ f64       ┆ f64     │
│            ┆            ┆                 ┆               ┆ u32            ┆           ┆         │
╞════════════╪════════════╪═════════════════╪═══════════════╪════════════════╪═══════════╪═════════╡
│ 2026-07-26 ┆ Papua      ┆ Merauke         ┆ 243           ┆ 1              ┆ 2161.03   ┆ 132.06  │
│ 2026-07-26 ┆ West       ┆ Sanggau         ┆ 138           ┆ 0              ┆ 2257.02   ┆ 198.95  │
│            ┆ Kalimantan ┆                 ┆               ┆                ┆           ┆         │
│ 2026-07-26 ┆ West       ┆ Ketapang        ┆ 63            ┆ 0              ┆ 636.93    ┆ 181.99  │
│            ┆ Kalimantan ┆                 ┆               ┆                ┆           ┆         │
│ 2026-07-26 ┆ West       ┆ Kayong Utara    ┆ 62            ┆ 1              ┆ 317.4     ┆ 18.95   │
│            ┆ Kalimantan ┆                 ┆               ┆                ┆           ┆         │
│ 2026-07-26 ┆ Papua      ┆ Mappi           ┆ 59            ┆ 0              ┆ 465.21    ┆ 30.18   │
└────────────┴────────────┴─────────────────┴───────────────┴────────────────┴───────────┴─────────┘

(939, 6)

shape: (5, 6)
┌────────────┬────────────────────┬───────────────┬───────────────────────┬───────────┬─────────┐
│ acq_date   ┆ province           ┆ hotspot_count ┆ high_confidence_count ┆ total_frp ┆ max_frp │
│ ---        ┆ ---                ┆ ---           ┆ ---                   ┆ ---       ┆ ---     │
│ str        ┆ str                ┆ u32           ┆ u32                   ┆ f64       ┆ f64     │
╞════════════╪════════════════════╪═══════════════╪═══════════════════════╪═══════════╪═════════╡
│ 2026-07-26 ┆ West Kalimantan    ┆ 441           ┆ 2                     ┆ 5424.03   ┆ 198.95  │
│ 2026-07-26 ┆ Papua              ┆ 354           ┆ 1                     ┆ 2989.11   ┆ 132.06  │
│ 2026-07-26 ┆ Central Kalimantan ┆ 144           ┆ 7                     ┆ 1096.95   ┆ 76.31   │
│ 2026-07-26 ┆ East Java          ┆ 91            ┆ 1                     ┆ 434.56    ┆ 34.02   │
│ 2026-07-26 ┆ Central Java       ┆ 68            ┆ 0                     ┆ 237.98    ┆ 29.55   │
└────────────┴────────────────────┴───────────────┴───────────────────────┴───────────┴─────────┘

(98245, 18)

shape: (5, 18)
┌──────────┬───────────┬────────────┬──────┬───┬─────────────┬─────────────┬──────────┬────────────┐
│ latitude ┆ longitude ┆ bright_ti4 ┆ scan ┆ … ┆ acquired_at ┆ geometry    ┆ province ┆ kabupaten_ │
│ ---      ┆ ---       ┆ ---        ┆ ---  ┆   ┆ _utc        ┆ ---         ┆ ---      ┆ kota       │
│ f64      ┆ f64       ┆ f64        ┆ f64  ┆   ┆ ---         ┆ binary      ┆ str      ┆ ---        │
│          ┆           ┆            ┆      ┆   ┆ datetime[μs ┆             ┆          ┆ str        │
│          ┆           ┆            ┆      ┆   ┆ , UTC]      ┆             ┆          ┆            │
╞══════════╪═══════════╪════════════╪══════╪═══╪═════════════╪═════════════╪══════════╪════════════╡
│ -8.81859 ┆ 140.97943 ┆ 328.55     ┆ 0.42 ┆ … ┆ 2026-07-26  ┆ b"\x01\x01\ ┆ Papua    ┆ Merauke    │
│          ┆           ┆            ┆      ┆   ┆ 04:34:00    ┆ x00\x00\x20 ┆          ┆            │
│          ┆           ┆            ┆      ┆   ┆ UTC         ┆ \xe6\x10…   ┆          ┆            │
│ -8.81766 ┆ 140.95972 ┆ 341.96     ┆ 0.42 ┆ … ┆ 2026-07-26  ┆ b"\x01\x01\ ┆ Papua    ┆ Merauke    │
│          ┆           ┆            ┆      ┆   ┆ 04:34:00    ┆ x00\x00\x20 ┆          ┆            │
│          ┆           ┆            ┆      ┆   ┆ UTC         ┆ \xe6\x10…   ┆          ┆            │
│ -8.81443 ┆ 140.97874 ┆ 328.47     ┆ 0.42 ┆ … ┆ 2026-07-26  ┆ b"\x01\x01\ ┆ Papua    ┆ Merauke    │
│          ┆           ┆            ┆      ┆   ┆ 04:34:00    ┆ x00\x00\x20 ┆          ┆            │
│          ┆           ┆            ┆      ┆   ┆ UTC         ┆ \xe6\x10…   ┆          ┆            │
│ -8.80832 ┆ 140.98946 ┆ 329.22     ┆ 0.42 ┆ … ┆ 2026-07-26  ┆ b"\x01\x01\ ┆ Papua    ┆ Merauke    │
│          ┆           ┆            ┆      ┆   ┆ 04:34:00    ┆ x00\x00\x20 ┆          ┆            │
│          ┆           ┆            ┆      ┆   ┆ UTC         ┆ \xe6\x10…   ┆          ┆            │
│ -8.70118 ┆ 140.58792 ┆ 339.31     ┆ 0.4  ┆ … ┆ 2026-07-26  ┆ b"\x01\x01\ ┆ Papua    ┆ Merauke    │
│          ┆           ┆            ┆      ┆   ┆ 04:34:00    ┆ x00\x00\x20 ┆          ┆            │
│          ┆           ┆            ┆      ┆   ┆ UTC         ┆ \xe6\x10…   ┆          ┆            │
└──────────┴───────────┴────────────┴──────┴───┴─────────────┴─────────────┴──────────┴────────────┘

In [47]:
firms30d.filter(
    pl.col("acq_date") == "2026-08-23",
    pl.col("province") == "East Kalimantan"
).height

306

In [48]:
(
    daily_kabkot
    .filter(
        pl.col("acq_date") == "2026-08-23"
    )
    .sort(
        "hotspot_count",
        descending=True,
    )
    .head(10)
)

shape: (10, 7)
┌────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────┬─────────┐
│ acq_date   ┆ province      ┆ kabupaten_kot ┆ hotspot_count ┆ high_confiden ┆ total_frp ┆ max_frp │
│ ---        ┆ ---           ┆ a             ┆ ---           ┆ ce_count      ┆ ---       ┆ ---     │
│ str        ┆ str           ┆ ---           ┆ u32           ┆ ---           ┆ f64       ┆ f64     │
│            ┆               ┆ str           ┆               ┆ u32           ┆           ┆         │
╞════════════╪═══════════════╪═══════════════╪═══════════════╪═══════════════╪═══════════╪═════════╡
│ 2026-08-23 ┆ Papua         ┆ Merauke       ┆ 560           ┆ 3             ┆ 3713.1    ┆ 75.77   │
│ 2026-08-23 ┆ South Sumatra ┆ Ogan Komering ┆ 279           ┆ 43            ┆ 5412.3    ┆ 126.32  │
│            ┆               ┆ Ilir          ┆               ┆               ┆           ┆         │
│ 2026-08-23 ┆ West          ┆ Ketapang      ┆ 227           ┆ 4             ┆ 1442.2    ┆ 198.53  │
│            ┆ Kalimantan    ┆               ┆               ┆               ┆           ┆         │
│ 2026-08-23 ┆ Papua         ┆ Mappi         ┆ 180           ┆ 0             ┆ 1938.99   ┆ 149.06  │
│ 2026-08-23 ┆ East          ┆ Berau         ┆ 132           ┆ 0             ┆ 1716.87   ┆ 163.78  │
│            ┆ Kalimantan    ┆               ┆               ┆               ┆           ┆         │
│ 2026-08-23 ┆ South Sumatra ┆ Musi          ┆ 124           ┆ 8             ┆ 1064.05   ┆ 67.14   │
│            ┆               ┆ Banyuasin     ┆               ┆               ┆           ┆         │
│ 2026-08-23 ┆ Central       ┆ Kotawaringin  ┆ 111           ┆ 1             ┆ 286.41    ┆ 15.0    │
│            ┆ Kalimantan    ┆ Timur         ┆               ┆               ┆           ┆         │
│ 2026-08-23 ┆ Maluku        ┆ Seram Bagian  ┆ 105           ┆ 0             ┆ 181.56    ┆ 5.71    │
│            ┆               ┆ Timur         ┆               ┆               ┆           ┆         │
│ 2026-08-23 ┆ Riau          ┆ Indragiri     ┆ 104           ┆ 9             ┆ 700.97    ┆ 54.58   │
│            ┆               ┆ Hilir         ┆               ┆               ┆           ┆         │
│ 2026-08-23 ┆ West Papua    ┆ Fakfak        ┆ 104           ┆ 2             ┆ 1687.92   ┆ 82.43   │
└────────────┴───────────────┴───────────────┴───────────────┴───────────────┴───────────┴─────────┘